### PR TITLE
Changes in scripts & nuspec to make it works(not final version though)

### PR DESCRIPTION
**Pull request by ialekseev**

### CODE REVIEW

**Comment by janhartmann** [comment]
Seems good - so its not possible to have the NuGet packaging command getting the id, description, etc. from the AssemblyInfo.cs (as of http://docs.nuget.org/create/nuspec-reference - see Replacement Tokens)?

**Comment by janhartmann** [comment]
Oh, then I need to pack like so - 'nuget pack MyProject.csproj'

**Comment by ialekseev** [comment]
Yes, or, as a last resort, you could always write one more script to sync content between AssemblyInfo and nuspec files.

**Comment by janhartmann** [comment]
Great, I look into it - thanks for your help! :-)

**Comment by ialekseev** [comment]
You are welcome, good luck ;)

**Comment by janhartmann** [comment]
I have changed a lot in the script and its now working perfectly. Thanks for the contribution ;-)

**Pull request closed without merging**
